services:
  synapnote-landingpage:
    image: synapnote-landingpage:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapnote-landingpage
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - synapnote-network

networks:
  synapnote-network:
    driver: bridge

